# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# $Id$
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/yan/Downloads/OpenDDS-3.16.1/ACE_wrappers/bin/mwc.pl -type gnuace /home/yan/Downloads/OpenDDS-3.16.1/DDS_TAOv2.mwc
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: Messenger_Idl Messenger_Publisher Messenger_Subscriber

depend: Messenger_Idl-depend Messenger_Publisher-depend Messenger_Subscriber-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)
.PHONY: $(REMAINING_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Idl $(@)
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Publisher $(@)
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Subscriber $(@)

.PHONY: Messenger_Idl
Messenger_Idl:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Idl all

.PHONY: Messenger_Idl-depend
Messenger_Idl-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Idl depend

.PHONY: Messenger_Publisher
Messenger_Publisher: Messenger_Idl
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Publisher all

.PHONY: Messenger_Publisher-depend
Messenger_Publisher-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Publisher depend

.PHONY: Messenger_Subscriber
Messenger_Subscriber: Messenger_Publisher
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Subscriber all

.PHONY: Messenger_Subscriber-depend
Messenger_Subscriber-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Messenger_Subscriber depend

project_name_list:
	@echo Messenger_Idl
	@echo Messenger_Publisher
	@echo Messenger_Subscriber
