/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module Messenger {

  @topic
  struct Message {
    string Name;
    float rating;
    string reviews;
    float distance;
    string subject;
    @key long subject_id;
    string address;
    string city;
    string state;
    string zip;
    string isOpen;
    string myLocation;
    string phoneNum;
    long count;
  };
};
